### ISSUE TITLE
About the different touchpad models

### ISSUE THREAD

**Issue by mdogwoop** [gabrielcasag/EFI-IDEAPAD-i5-8250U-330-15IKB-OPENCORE#3]
There are different touchpad models for laptops these days, and there are Elan and Synaptics versions. But unfortunately my laptop is using Synaptics, so I can't start this project normally, just like this picture
![IMG_20221024_132944](https://user-images.githubusercontent.com/64186089/197455119-28a64a6e-4a0f-4694-a4ff-3daac7505230.jpg)

**Comment by gabrielcasag** [comment]
hey @mdogwoop 

if you have an synaptic trackpad and using my EFI, you have to adjust that to fit your scenario since as the README says my trackpad is ELAN

I think that changing the voodoi2celan by the voodooi2csynaptics in the kext folder and adjust the .plist its enough

more info: https://github.com/VoodooI2C/VoodooI2C
and
https://dortania.github.io/Getting-Started-With-ACPI/Laptops/trackpad.html

**Comment by mdogwoop** [comment]
ok i will try

**Comment by gabrielcasag** [comment]
hey @mdogwoop, closing that in this moment. 

I just launch a new release of the EFI folder, remaking the SSDTs patches, give it a try and feel free to open another issue if u have a problem
