### ISSUE TITLE
Trackpad Setting in MacOS Ventura

### ISSUE THREAD

**Issue by luisonog** [gabrielcasag/EFI-IDEAPAD-i5-8250U-330-15IKB-OPENCORE#4]
Using the OC 0.8.5 to install the MacOS Ventura results in a working trackpad but without the option to change its settings in System Preferences. 

Any insights on how to solve this?

Thanks a bunch. Keep up the good work!

**Comment by gabrielcasag** [comment]
Hey @luisonog, what good news!

About the trackpad a point of attention it's that my EFI is based on my specific hardware and even being the same notebook there may be different components.

In my case I have [verified my hardware](https://dortania.github.io/OpenCore-Install-Guide/find-hardware.html#finding-hardware-using-windows) and my trackpad is an "ELAN pointing device" and because that In my EFI I'm using the [VoodooI2CElan.kext](https://github.com/VoodooI2C/VoodooI2CELAN/tree/3cb69b61fc4dc4eab127787455d0f1c337a3df0c).

If you have other type of device you have to choose the specific kext.

There are some links to help:
https://voodooi2c.github.io/#Installation/Installation
https://dortania.github.io/Getting-Started-With-ACPI/Laptops/trackpad.html

**Comment by gabrielcasag** [comment]
hey @luisonog, closing that in this moment. 

I just launch a new release of the EFI folder, remaking the SSDTs patches, give it a try and feel free to open another issue if u have a problem

**Comment by gabrielcasag** [comment]
hey @luisonog, closing that in this moment. 

I just launch a new release of the EFI folder, remaking the SSDTs patches, give it a try and feel free to open another issue if u have a problem
